spring:
  profiles:
    active: dev

  #  所有环境通用的配置，放在这里
  # 404 交给异常处理器处理
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  # 开发环境配置
  # 数据源配置，请修改为你项目的实际配置
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: rootadsa
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

